# ============================================================
#  ROTAZIONE PORTE EMULATORE (security-through-obscurity, layer 1)
#
#  Randomizza ad ogni esecuzione le 3 porte non-web dell'emulatore:
#    - game.port     (Netty TCP server, default 3000)
#    - rcon.port     (admin remote console, default 3001, loopback)
#    - ws.nitro.port (WebSocket nitro client, default 2096)
#
#  Le porte HTTP (8080 CMS, 8090 client-dist) restano fisse perche'
#  devono essere conosciute dall'utente che apre l'URL nel browser.
#  La vera difesa di queste sta in Cloudflare Spectrum (vedi SETUP.md).
#
#  Coerentemente aggiorna:
#    - Arcturus-MS\config.ini (game.port + rcon.port)
#    - DB ms.emulator_settings (ws.nitro.port)
#    - client-dist\renderer-config.json (socket.url)
#    - Habboproject\CMS\react\renderer-config.json (socket.url)
#  Scrive le porte correnti in Github\.ports.current (gitignored).
#
#  Uso:  powershell -File rotate_ports.ps1 [-NoRestart]
# ============================================================
param([switch]$NoRestart)
$ErrorActionPreference = 'Stop'

$G    = 'C:\Users\vincenzokatrielgiuva\Desktop\Github'
$EMU  = "$G\Arcturus-MS"
$CMSReact = "$G\Habboproject\CMS\react"
$LIVE = "$G\client-dist"
$MYSQL = 'C:\xampp\mysql\bin\mysql.exe'
$JAVA = 'C:\Program Files\Microsoft\jdk-11.0.31.11-hotspot\bin\java.exe'

function Get-FreePort {
    param([int]$min, [int]$max, [int[]]$exclude)
    for ($i=0; $i -lt 200; $i++) {
        $p = Get-Random -Minimum $min -Maximum $max
        if ($exclude -contains $p) { continue }
        if (Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue) { continue }
        return $p
    }
    throw "Could not find a free port in $min..$max after 200 tries"
}

Write-Host '== 1. Genero 3 porte random (35000..45000) ...' -ForegroundColor Cyan
$reserved = @(80, 443, 3306, 8080, 8081, 8090)
$gamePort = Get-FreePort -min 35000 -max 45000 -exclude $reserved
$rconPort = Get-FreePort -min 35000 -max 45000 -exclude ($reserved + @($gamePort))
$wsPort   = Get-FreePort -min 35000 -max 45000 -exclude ($reserved + @($gamePort, $rconPort))
Write-Host "   game.port     = $gamePort"
Write-Host "   rcon.port     = $rconPort"
Write-Host "   ws.nitro.port = $wsPort"

Write-Host '== 2. Stop emu corrente (se attivo) ...' -ForegroundColor Cyan
$listening = Get-NetTCPConnection -State Listen -LocalPort 2096,3000,3001 -ErrorAction SilentlyContinue
foreach ($conn in $listening) {
    try { Stop-Process -Id $conn.OwningProcess -Force -ErrorAction SilentlyContinue; Write-Host "   stopped PID $($conn.OwningProcess)" } catch {}
}
Start-Sleep -Seconds 2

Write-Host '== 3. Aggiorno Arcturus-MS\config.ini ...' -ForegroundColor Cyan
$cfg = Get-Content "$EMU\config.ini"
$cfg = $cfg -replace '^game\.port=\d+', "game.port=$gamePort"
$cfg = $cfg -replace '^rcon\.port=\d+', "rcon.port=$rconPort"
Set-Content -Path "$EMU\config.ini" -Value $cfg -Encoding ASCII
Write-Host "   game.port/rcon.port aggiornati"

Write-Host '== 4. Aggiorno DB emulator_settings ws.nitro.port ...' -ForegroundColor Cyan
$sql = "UPDATE emulator_settings SET value='$wsPort' WHERE ``key``='ws.nitro.port';"
& $MYSQL -u root ms -e $sql 2>$null | Out-Null
Write-Host "   ws.nitro.port = $wsPort scritto su ms.emulator_settings"

Write-Host '== 5. Aggiorno renderer-config.json (CMS + client-dist) ...' -ForegroundColor Cyan
foreach ($cfgPath in @("$CMSReact\renderer-config.json", "$LIVE\renderer-config.json")) {
    if (Test-Path $cfgPath) {
        $content = Get-Content $cfgPath -Raw
        $newContent = [regex]::Replace($content, '"socket\.url"\s*:\s*"ws://[^"]+"', "`"socket.url`": `"ws://127.0.0.1:$wsPort`"")
        Set-Content -Path $cfgPath -Value $newContent -NoNewline -Encoding UTF8
        Write-Host "   $cfgPath aggiornato"
    }
}

Write-Host '== 6. Scrivo .ports.current (gitignored) ...' -ForegroundColor Cyan
@"
# Generated by rotate_ports.ps1 - DO NOT COMMIT
# Last rotation: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
game.port=$gamePort
rcon.port=$rconPort
ws.nitro.port=$wsPort
"@ | Set-Content -Path "$G\.ports.current" -Encoding UTF8

if ($NoRestart) {
    Write-Host '== Skipped restart (-NoRestart) ==' -ForegroundColor Yellow
    return
}

Write-Host '== 7. Riavvio emu ...' -ForegroundColor Cyan
Start-Process -FilePath $JAVA `
    -ArgumentList '-Xms512m','-Xmx2g','-XX:+UseG1GC','-XX:MaxGCPauseMillis=100','-jar','Habbo-3.5.5-jar-with-dependencies.jar' `
    -WorkingDirectory $EMU -RedirectStandardOutput "$EMU\emu.out.log" -RedirectStandardError "$EMU\emu.err.log" -WindowStyle Hidden

Write-Host '== 8. Attendo che le 3 porte siano in LISTEN ...' -ForegroundColor Cyan
$deadline = (Get-Date).AddSeconds(45)
$allUp = $false
while ((Get-Date) -lt $deadline) {
    $up = @($gamePort, $rconPort, $wsPort) | ForEach-Object {
        [bool](Get-NetTCPConnection -State Listen -LocalPort $_ -ErrorAction SilentlyContinue)
    }
    if (-not ($up -contains $false)) { $allUp = $true; break }
    Start-Sleep -Seconds 1
}

Write-Host ''
if ($allUp) {
    Write-Host '== Done. Nuove porte attive: ==' -ForegroundColor Green
    Write-Host "   game: $gamePort   rcon: $rconPort   ws-nitro: $wsPort"
    Write-Host '   Client: refresh del browser per ricevere il renderer-config aggiornato.'
} else {
    Write-Host '== Warning: una o piu` porte non sono ancora in LISTEN dopo 45s.' -ForegroundColor Yellow
    Write-Host '   Controlla Arcturus-MS\emu.out.log per errori.'
}
